/* Generated By:JavaCC: Do not edit this line. EG1.java */
package main;
import java.util.Stack;

public class EG1 implements EG1Constants {
  public static final String nl = System.getProperty("line.separator");

  final public String start() throws ParseException {
  String s = "";
  String out = "";
  Token t;
    System.out.print("START ");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
      case 26:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 19:
          s = quote();
          break;
        case 26:
          s = list();
          break;
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        out += s;
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        s = text();
        out += s;
        break;
      case PARA:
        jj_consume_token(PARA);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case PARA:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 26:
      case 27:
      case 31:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
    {
      System.out.println("END");
    }
    {if (true) return out;}
    throw new Error("Missing return statement in function");
  }

  final public String text() throws ParseException {
  String s;
  Token t;
  String out = "";
    System.out.print("text ");
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
        s = typo();
        break;
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        if (jj_2_2(2147483647)) {
          s = simpleTag();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case NUMBER:
          case WORD:
          case DELO:
          case BOLD:
          case ITALICS:
          case 18:
          case 19:
          case 20:
          case 21:
          case 27:
          case 31:
            if (jj_2_1(2147483647)) {
              s = format();
            } else {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case NUMBER:
              case WORD:
              case 18:
              case 19:
              case 20:
              case 21:
                s = plainTextPiece();
                break;
              case BOLD:
                t = jj_consume_token(BOLD);
          s = t.image;
                break;
              case ITALICS:
                t = jj_consume_token(ITALICS);
          s = t.image;
                break;
              default:
                jj_la1[4] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
            }
            break;
          default:
            jj_la1[5] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      out += s;
      System.out.println(" | " + out);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
    }
    {if (true) return out;}
    throw new Error("Missing return statement in function");
  }

  final public String number() throws ParseException {
  Token t;
    System.out.print("number ");
    t = jj_consume_token(NUMBER);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public String word() throws ParseException {
  Token t;
    System.out.print("word ");
    t = jj_consume_token(WORD);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public String plainTextPiece() throws ParseException {
  String s;
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
    case WORD:
    System.out.print("ptp ");
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WORD:
        s = word();
        break;
      case NUMBER:
        s = number();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    {if (true) return s;}
      break;
    case 18:
      jj_consume_token(18);
    {if (true) return "<";}
      break;
    case 19:
      jj_consume_token(19);
    {if (true) return ">";}
      break;
    case 20:
      jj_consume_token(20);
    {if (true) return "*";}
      break;
    case 21:
      jj_consume_token(21);
    {if (true) return "/";}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String wiki() throws ParseException {
  String s;
  Token t;
  String out = "";
    s = alnum();
    out += s;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 22:
      case 23:
      case 24:
      case 25:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 22:
        jj_consume_token(22);
        out += ".";
        break;
      case 23:
        jj_consume_token(23);
        out += "-";
        break;
      case 24:
        jj_consume_token(24);
        out += "_";
        break;
      case 25:
        jj_consume_token(25);
        out += ":";
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      s = alnum();
      out += s;
    }
    {if (true) return "{wiki=\u005c"" + out + "\u005c"}";}
    throw new Error("Missing return statement in function");
  }

  final public String emailTag() throws ParseException {
  Token t;
    jj_consume_token(18);
    t = jj_consume_token(E_MAIL);
    jj_consume_token(19);
    {if (true) return "email=\u005c"" + t.image + "\u005c"";}
    throw new Error("Missing return statement in function");
  }

  final public String alnum() throws ParseException {
  String s;
  String st = "";
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WORD:
        s = word();
      st += s;
        break;
      case NUMBER:
        s = number();
      st += s;
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case WORD:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
    }
    {if (true) return st;}
    throw new Error("Missing return statement in function");
  }

  final public String url() throws ParseException {
  Token t;
    t = jj_consume_token(URL);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public String link() throws ParseException {
  String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
    case WORD:
      s = wiki();
      break;
    case URL:
      s = url();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String imageUrl() throws ParseException {
  String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 26:
      jj_consume_token(26);
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    s = url();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 26:
      jj_consume_token(26);
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    {if (true) return "iurl=[" + s + "]";}
    throw new Error("Missing return statement in function");
  }

  final public String image() throws ParseException {
  Token t;
  String s;
  String url;
  Integer nalign = 0; // 0 - brak, 1 - lewo, 2 - prawo, 3 - oba
  Integer width =-1;
  Integer height =-1;
  String title = "";
    jj_consume_token(27);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 26:
      jj_consume_token(26);
    nalign += 1;
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    s = url();
    url = s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 26:
      jj_consume_token(26);
    nalign += 2;
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      jj_consume_token(28);
      t = jj_consume_token(NUMBER);
      width = Integer.valueOf(t.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WORD:
        t = jj_consume_token(WORD);
        if (!(t.image).equals("x")) {if (true) throw new IllegalArgumentException(t.image);}
        t = jj_consume_token(NUMBER);
        height = Integer.valueOf(t.image);
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 29:
      jj_consume_token(29);
      t = jj_consume_token(WORD);
    title = t.image;
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(30);
    String align = "";
    switch (nalign)
    {
      case 0 : // fall
      case 1 : align = "left";
      break;
      case 2 : align = "right";
      break;
      case 3 : align = "middle";
      break;
    }
    if (height == - 1) {if (true) return String.format("<img src=\u005c"%s\u005c" alt=\u005c"%s\u005c" align=\u005c"%s\u005c" width=\u005c"%d\u005c">", url, title, align, width);}
    else {if (true) return String.format("<img src=\u005c"%s\u005c" alt=\u005c"%s\u005c" align=\u005c"%s\u005c" width=\u005c"%d\u005c" height=\u005c"%d\u005c">", url, title, align, width, height);}
    throw new Error("Missing return statement in function");
  }

  final public String linkTag() throws ParseException {
  Token t;
  String s;
  String url;
  String title = "";
    jj_consume_token(31);
    s = link();
      url = s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 29:
      jj_consume_token(29);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WORD:
        t = jj_consume_token(WORD);
          title = t.image;
        break;
      case 27:
        s = image();
          title = s;
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(32);
    {if (true) return String.format("<a href=\u005c"%s\u005c">%s</a>", url, title);}
    throw new Error("Missing return statement in function");
  }

  final public String typo() throws ParseException {
    System.out.print("typo ");
    jj_consume_token(ARROW_RIGHT);
    {if (true) return "\u00e2\u20ac\u015f";}
    throw new Error("Missing return statement in function");
  }

  final public String simpleTag() throws ParseException {
  String s;
    System.out.print("simple ");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOLD:
      s = bold();
      break;
    case ITALICS:
      s = italics();
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String bold() throws ParseException {
  String s = "";
  String out = "";
    System.out.print("bold ");
    jj_consume_token(BOLD);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARROW_RIGHT:
    case NUMBER:
    case WORD:
    case DELO:
    case ITALICS:
    case 18:
    case 19:
    case 20:
    case 21:
    case 27:
    case 31:
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ARROW_RIGHT:
          s = typo();
          break;
        case ITALICS:
          s = italics();
          break;
        case DELO:
        case 18:
        case 27:
        case 31:
          s = format();
          break;
        case NUMBER:
        case WORD:
        case 19:
        case 20:
        case 21:
          s = plainTextPiece();
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
          out += s;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ARROW_RIGHT:
        case NUMBER:
        case WORD:
        case DELO:
        case ITALICS:
        case 18:
        case 19:
        case 20:
        case 21:
        case 27:
        case 31:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_5;
        }
      }
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    jj_consume_token(BOLD);
    {if (true) return "<b>" + out + "</b>";}
    throw new Error("Missing return statement in function");
  }

  final public String italics() throws ParseException {
  String s = "";
  String out = "";
    System.out.print("italics ");
    jj_consume_token(ITALICS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARROW_RIGHT:
    case NUMBER:
    case WORD:
    case DELO:
    case BOLD:
    case 18:
    case 19:
    case 20:
    case 21:
    case 27:
    case 31:
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ARROW_RIGHT:
          //s = bold()
                    //|	s = text() // TODO: text __BEZ__ bolda!
                    s = typo();
          break;
        case BOLD:
          s = bold();
          break;
        case DELO:
        case 18:
        case 27:
        case 31:
          s = format();
          break;
        case NUMBER:
        case WORD:
        case 19:
        case 20:
        case 21:
          s = plainTextPiece();
          break;
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
          out += s;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ARROW_RIGHT:
        case NUMBER:
        case WORD:
        case DELO:
        case BOLD:
        case 18:
        case 19:
        case 20:
        case 21:
        case 27:
        case 31:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_6;
        }
      }
      break;
    default:
      jj_la1[30] = jj_gen;
      ;
    }
    jj_consume_token(ITALICS);
    {if (true) return "<i>" + out + "</i>";}
    throw new Error("Missing return statement in function");
  }

  final public String ocTag() throws ParseException {
  String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 18:
      s = emailTag();
    {if (true) return s;}
      break;
    case DELO:
      s = htmlTag();
    {if (true) return s;}
      break;
    case 27:
      s = image();
    {if (true) return s;}
      break;
    case 31:
      s = linkTag();
    {if (true) return s;}
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String htmlTag() throws ParseException {
  String s;
    s = delTag();
    {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String delTag() throws ParseException {
  String s;
    jj_consume_token(DELO);
    s = text();
    jj_consume_token(DELC);
    {if (true) return "<del>" + s + "</del>";}
    throw new Error("Missing return statement in function");
  }

//String text() :
//{
//  Token t;
//  String s = "";
//  String out = "";
//}
//{
//  {
//    System.out.print("text ");
//  }
//  (
//    (
//      (
//        (
//          "*"
//          {
//            out += "*";
//          }
//        | "/"
//          {
//            out += "/";
//          }
//        | "_"
//          {
//            out += "_";
//          }
//        )?
//        s = word() // XXX: tymczasowe
//      | s = format()
//      | s = number()
//      )
//      {
//        out += s;
//      }
//    )+
//  )
//  //  < EOF >
//  {
//    return out;
//  }
//}
  final public String format() throws ParseException {
  String s;
    s = ocTag();
    {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String ulist() throws ParseException {
  String s;
  String out = "";
  Integer prevNestLevel = 0;
  Integer nestLevel = 0;
  Integer spaces = 0;
    label_7:
    while (true) {
      s = "";
      jj_consume_token(26);
      spaces = 1;
      label_8:
      while (true) {
        jj_consume_token(26);
      spaces++;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 26:
          ;
          break;
        default:
          jj_la1[32] = jj_gen;
          break label_8;
        }
      }
      jj_consume_token(20);
      nestLevel = spaces / 2;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        s = text();
        break;
      default:
        jj_la1[33] = jj_gen;
        ;
      }
      if (prevNestLevel < nestLevel) for (; prevNestLevel < nestLevel; prevNestLevel++)
      {
        out += new String(new char [ prevNestLevel ]).replace('\u005c0', '\u005ct'); // indent
        out += "<ul>" + nl;
      }
      else for (; prevNestLevel > nestLevel; prevNestLevel--)
      {
        out += new String(new char [ prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
        out += "</ul>" + nl;
      }
      out += new String(new char [ prevNestLevel ]).replace('\u005c0', '\u005ct'); // indent
      out += "<li>" + s + "</li>" + nl;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PARA:
        jj_consume_token(PARA);
        break;
      case 0:
        jj_consume_token(0);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_7;
      }
    }
    for (; prevNestLevel > 0; prevNestLevel--)
    {
      out += new String(new char [ prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
      out += "</ul>" + nl;
    }
    {if (true) return out;}
    throw new Error("Missing return statement in function");
  }

  final public String olist() throws ParseException {
  String s;
  String out = "";
  Integer prevNestLevel = 1;
  Integer nestLevel = 0;
  Integer spaces = 0;
  Stack < Integer > openedLis = new Stack < Integer > ();
    System.out.print("ol ");
    out += "<ol>" + nl;
    label_9:
    while (true) {
      s = "";
      jj_consume_token(26);
      spaces = 1;
      label_10:
      while (true) {
        jj_consume_token(26);
      spaces++;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 26:
          ;
          break;
        default:
          jj_la1[36] = jj_gen;
          break label_10;
        }
      }
      jj_consume_token(23);
      nestLevel = spaces / 2;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        s = text();
        break;
      default:
        jj_la1[37] = jj_gen;
        ;
      }
      // todo: w petli
      while (prevNestLevel >= nestLevel && !openedLis.isEmpty())
      {
        if (prevNestLevel == openedLis.peek())
        {
          out += new String(new char [ openedLis.size() + prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
          out += "</li>" + nl;
          openedLis.pop();
        }
        if (prevNestLevel == nestLevel) break;
        else
        {
          out += new String(new char [ openedLis.size() + prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
          out += "</ol>" + nl;
          prevNestLevel--;
        }
      }
      if (prevNestLevel < nestLevel) for (; prevNestLevel < nestLevel; prevNestLevel++)
      {
        out += new String(new char [ prevNestLevel + openedLis.size() ]).replace('\u005c0', '\u005ct'); // indent
        out += "<ol>" + nl;
      }
      System.out.println(String.format("nl=%d  pnl=%d", nestLevel, prevNestLevel));
      out += new String(new char [ prevNestLevel + openedLis.size() ]).replace('\u005c0', '\u005ct'); // indent
      out += "<li>" + s + nl;
      openedLis.push(nestLevel);
      jj_consume_token(PARA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_9;
      }
    }
    {}
    for (; prevNestLevel > 0; prevNestLevel--)
    {
      if (prevNestLevel == openedLis.peek())
      {
        out += new String(new char [ openedLis.size() + prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
        out += "</li>" + nl;
        openedLis.pop();
      }
      out += new String(new char [ openedLis.size() + prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
      out += "</ol>" + nl;
    }
    {if (true) return out;}
    throw new Error("Missing return statement in function");
  }

  final public String list() throws ParseException {
  String s;
    if (jj_2_3(3)) {
      // wystarczy, gdy pierwszy poziom np. podwójnie zagnie¿d¿ony?
        s = ulist();
    {if (true) return s;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        s = olist();
    {if (true) return s;}
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String quote() throws ParseException {
  String s = "";
  String out = "";
  Integer prevNestLevel = 0;
  Integer nestLevel = 0;
    label_11:
    while (true) {
      s = "";
      label_12:
      while (true) {
        jj_consume_token(19);
      nestLevel++;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 19:
          ;
          break;
        default:
          jj_la1[40] = jj_gen;
          break label_12;
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARROW_RIGHT:
      case NUMBER:
      case WORD:
      case DELO:
      case BOLD:
      case ITALICS:
      case 18:
      case 19:
      case 20:
      case 21:
      case 27:
      case 31:
        s = text();
        break;
      default:
        jj_la1[41] = jj_gen;
        ;
      }
      if (prevNestLevel < nestLevel) for (; prevNestLevel < nestLevel; prevNestLevel++)
      {
        out += new String(new char [ prevNestLevel ]).replace('\u005c0', '\u005ct'); // indent
        out += "<blockquote>" + nl;
      }
      else for (; prevNestLevel > nestLevel; prevNestLevel--)
      {
        out += new String(new char [ prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
        out += "</blockquote>" + nl;
      }
      out += new String(new char [ prevNestLevel ]).replace('\u005c0', '\u005ct'); // indent
      out += s + nl;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PARA:
        jj_consume_token(PARA);
        break;
      case 0:
        jj_consume_token(0);
        break;
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      nestLevel = 0;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
        ;
        break;
      default:
        jj_la1[43] = jj_gen;
        break label_11;
      }
    }
    for (; prevNestLevel > 0; prevNestLevel--)
    {
      out += new String(new char [ prevNestLevel - 1 ]).replace('\u005c0', '\u005ct'); // indent
      out += "</blockquote>" + nl;
    }
    {if (true) return out;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3R_77() {
    if (jj_3R_85()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) return true;
    }
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(29)) return true;
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(DELO)) return true;
    if (jj_3R_43()) return true;
    if (jj_scan_token(DELC)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(WORD)) return true;
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(28)) return true;
    if (jj_scan_token(NUMBER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(27)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) jj_scanpos = xsp;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(ITALICS)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(BOLD)) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_71() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) return true;
    }
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_43() {
    Token xsp;
    if (jj_3R_57()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_57()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    Token xsp;
    if (jj_3R_42()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_42()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_58()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    }
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(ITALICS)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) jj_scanpos = xsp;
    if (jj_scan_token(ITALICS)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(URL)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_31() {
    Token xsp;
    if (jj_3R_41()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_3R_85()) return true;
    return false;
  }

  private boolean jj_3R_72() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) return true;
    }
    return false;
  }

  private boolean jj_3R_63() {
    Token xsp;
    if (jj_3R_72()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_72()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(BOLD)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) jj_scanpos = xsp;
    if (jj_scan_token(BOLD)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(E_MAIL)) return true;
    if (jj_scan_token(19)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) return true;
    }
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(26)) return true;
    Token xsp;
    if (jj_3R_26()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_26()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    if (jj_3R_19()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_19()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(ARROW_RIGHT)) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_scan_token(22)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) return true;
    }
    }
    }
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_63()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_64()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(29)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(31)) return true;
    if (jj_3R_39()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) jj_scanpos = xsp;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(19)) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_3R_86()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public EG1TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[44];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4080000,0x4080000,0x883cd02e,0x8c3cd02e,0x3cc00c,0x883cd00c,0x883cd00e,0x883cd00e,0xc,0x3c000c,0x3c00000,0x3c00000,0xc,0xc,0x10c,0x4000000,0x4000000,0x4000000,0x4000000,0x8,0x10000000,0x20000000,0x8000008,0x20000000,0xc000,0x883c900e,0x883c900e,0x883c900e,0x883c500e,0x883c500e,0x883c500e,0x88041000,0x4000000,0x883cd00e,0x21,0x4000000,0x4000000,0x883cd00e,0x4000000,0x4000000,0x80000,0x883cd00e,0x21,0x80000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public EG1(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public EG1(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new EG1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public EG1(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new EG1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public EG1(EG1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(EG1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 44; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[33];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 44; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 33; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
