/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUBO = 3;
  /** RegularExpression Id. */
  int SUBC = 4;
  /** RegularExpression Id. */
  int BOLD = 5;
  /** RegularExpression Id. */
  int ITALIC = 6;
  /** RegularExpression Id. */
  int UNDERSCORE = 7;
  /** RegularExpression Id. */
  int SINGLE_ASTERISK = 8;
  /** RegularExpression Id. */
  int SPECIAL_TOKENS = 9;
  /** RegularExpression Id. */
  int TEXT = 10;
  /** RegularExpression Id. */
  int WORD = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int WHITESPACE = 14;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"<sub>\"",
    "\"</sub>\"",
    "\"**\"",
    "\"//\"",
    "\"__\"",
    "<SINGLE_ASTERISK>",
    "<SPECIAL_TOKENS>",
    "<TEXT>",
    "<WORD>",
    "<DIGIT>",
    "<LETTER>",
    "<WHITESPACE>",
    "<SPECIAL_CHARS>",
  };

}
