/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW_RIGHT = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int WORD = 3;
  /** RegularExpression Id. */
  int ALNUM = 4;
  /** RegularExpression Id. */
  int PARA = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int HR = 8;
  /** RegularExpression Id. */
  int URL = 9;
  /** RegularExpression Id. */
  int DOMAIN = 10;
  /** RegularExpression Id. */
  int E_MAIL = 11;
  /** RegularExpression Id. */
  int E_MAIL_USERNAME = 12;
  /** RegularExpression Id. */
  int DELO = 13;
  /** RegularExpression Id. */
  int DELC = 14;
  /** RegularExpression Id. */
  int BOLD = 15;
  /** RegularExpression Id. */
  int ITALICS = 16;
  /** RegularExpression Id. */
  int UNDERLINE = 17;
  /** RegularExpression Id. */
  int NO_FORAT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"->\"",
    "<NUMBER>",
    "<WORD>",
    "<ALNUM>",
    "<PARA>",
    "<DIGIT>",
    "<LETTER>",
    "<HR>",
    "<URL>",
    "<DOMAIN>",
    "<E_MAIL>",
    "<E_MAIL_USERNAME>",
    "\"<del>\"",
    "\"</del>\"",
    "\"**\"",
    "\"//\"",
    "\"__\"",
    "\"%%\"",
    "\"<\"",
    "\">\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\".\"",
    "\"_\"",
    "\":\"",
    "\" \"",
    "\"{{\"",
    "\"?\"",
    "\"|\"",
    "\"}}\"",
    "\"[[\"",
    "\"]]\"",
    "\"=\"",
  };

}
